apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: betix
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: betix-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /dashboard
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
